# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vclaim < Formula
  desc "Regex workbench with formal guarantees. automata theory behind a dead-simple c"
  homepage "https://github.com/ousatov-ua/vclaim"
  url "https://github.com/ousatov-ua/vclaim/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "720b69802e8c482bc765dd67a20f509d936141118378cb7bcb02a09df14297d1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/vclaim/releases/download/v0.1.0/vclaim-0.1.0-darwin-arm64.tar.gz"
      sha256 "06f110caf458edfe0430494af631964e6b2cf41ea6f750ed90d967d66dd552bc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/vclaim/releases/download/v0.1.0/vclaim-0.1.0-linux-amd64.tar.gz"
      sha256 "4e76b7181943ad86408a14d8ccdb3e00d823bc1ed9b89799839c86fd379c771e"
    end
  end

  def install
    bin.install "vclaim"
  end

  test do
    system "#{bin}/vclaim", "--version"
  end
end
