# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vet < Formula
  desc "Regex workbench with formal guarantees. automata theory behind a dead-simple c"
  homepage "https://github.com/ousatov-ua/vet"
  url "https://github.com/ousatov-ua/vet/archive/refs/tags/v0.1.0.tar.gz"
  version "0.1.0"
  sha256 "1faf03ae9239af369230f0574656871d80b15a2c425254442c21d3b39f1aa309"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/vet/releases/download/v0.1.0/vet-0.1.0-darwin-arm64.tar.gz"
      sha256 "3b3cd9798126dc43dbf48891553cb48e0578d0dc30e9f4d3c68995625dedbdf6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/vet/releases/download/v0.1.0/vet-0.1.0-linux-amd64.tar.gz"
      sha256 "a10bbf4198726d210674065e1fcf5cb81026d17649a5dffac2f5b414a0323c7c"
    end
  end

  def install
    bin.install "vet"
  end

  test do
    system "#{bin}/vet", "--version"
  end
end
