# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vet < Formula
  desc "Regex workbench with formal guarantees. automata theory behind a dead-simple c"
  homepage "https://github.com/ousatov-ua/vet"
  url "https://github.com/ousatov-ua/vet/archive/refs/tags/v0.1.2.tar.gz"
  version "0.1.2"
  sha256 "4f6ee88400c66e2c2e371b96e0252dd51c237741c3da80f192fe2709f635b217"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ousatov-ua/vet/releases/download/v0.1.2/vet-0.1.2-darwin-arm64.tar.gz"
      sha256 "2d55c7526c849841d42c27ea09517fdb146e8eb3b71a92054d3d88ebb8ba6b79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ousatov-ua/vet/releases/download/v0.1.2/vet-0.1.2-linux-amd64.tar.gz"
      sha256 "264f78425621680bf43edd68f9e9f86b48516f260c0447d3caa81921ff051e20"
    end
  end

  def install
    bin.install "vet"
  end

  test do
    system "#{bin}/vet", "--version"
  end
end
